version: '3'
services:
  authentication-service:
    container_name: authentication-service
    build: .
    ports:
      - "2512:2512"
    networks:
      - cf-network
networks:
  cf-network:
    external: true
