version: '3'
services:
  authentication-service:
    container_name: authentication-service
    build: .
    ports:
      - "26010:26010"
    networks:
      - bbu-network
networks:
  bbu-network:
    external: true
