version: '3'
services:
  authentication-service:
    build: .
    ports:
      - "2512:2512"
    depends_on:
      - msa-config-server
      - report-service
      - user-service
    networks:
      - cf-network

networks:
  cf-network:
    external: true
