CREATE TABLE USER_REFRESH_TOKENS (
    ID VARCHAR(255) NOT NULL PRIMARY KEY,
    REFRESH_TOKEN  VARCHAR(MAX) NOT NULL,
    ACCESS_TOKEN VARCHAR(MAX) NOT NULL,
    EXPIRE_ON DATETIME2 NOT NULL,
    DEVICE_ID VARCHAR(100) NULL,
    USER_ID VARCHAR(100) NOT NULL,
    CLIENT_ID VARCHAR(100) NULL,
    CREATED_BY VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME2 NOT NULL,
    UPDATED_BY VARCHAR(255)  NULL,
    UPDATED_AT DATETIME2  NULL,
    DELETED_BY VARCHAR(255)  NULL,
    DELETED_AT DATETIME2  NULL,
    STATUS NVARCHAR(3) NULL DEFAULT 'ACT'
);
