CREATE TABLE RESPONSE_CODES (
    ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    CREATED_AT DATETIME2 NULL,
    CREATED_BY NVARCHAR(255) NULL,
    UPDATED_AT DATETIME2 NULL,
    UPDATED_BY NVARCHAR(255) NULL,
    CODE NVARCHAR(255) NOT NULL UNIQUE,
    DESCRIPTION NVARCHAR(255) NULL,
    HTTP_STATUS NVARCHAR(255) NULL,
    [KEY] NVARCHAR(255) NULL,
    MESSAGE_EN NVARCHAR(255) NULL,
    MESSAGE_CN NVARCHAR(255) NULL,
    MESSAGE_KM NVARCHAR(255) NULL,
    [TYPE] NVARCHAR(255) NULL,
    SERVICE_TYPE NVARCHAR(100) NULL,
    DELETED_AT DATETIME2 NULL,
    DELETED_BY NVARCHAR(100) NULL,
    STATUS NVARCHAR(3) NULL DEFAULT 'ACT'
);
