CREATE TABLE dbo.ROLES (
    ID VARCHAR(36) NOT NULL,
    CODE VARCHAR(100) NOT NULL,
    [NAME] VARCHAR(100) NOT NULL,
    CONVENTION VARCHAR(100) NULL,
    [LEVEL] INT NULL,
    STATUS VARCHAR(100) NULL,
    DESCRIPTION VARCHAR(MAX) NULL,
    CONSTRAINT PK_ROLES PRIMARY KEY (ID)
);